apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-sdk-direct
  labels:
    app: subscriber-sdk-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-sdk-direct
  template:
    metadata:
      labels:
        app: subscriber-sdk-direct
        azure.workload.identity/use: "true" 
    spec:
      serviceAccountName: subscriber-sdk-direct
      containers:
      - name: subscriber-sdk-direct
        image: $REGISTRY_NAME/subscriber-sdk-direct:latest
        ports:
        - containerPort: 8000
        env:
          - name: SERVICE_BUS_NAMESPACE
            value: $SERVICE_BUS_NAMESPACE
        imagePullPolicy: Always
        # TODO - set env vars for connection string, topic name, subscription name