apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notifications-pubsub-subscriber-2
spec:
  # https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-topics/
  type: pubsub.azure.servicebus.topics
  initTimeout: 1m
  version: v1
  metadata:
  - name: consumerID
    value: task-notification-subscriber-2
  - name: connectionString
    secretKeyRef:
      name: SERVICE_BUS_CONNECTION_STRING
      key: SERVICE_BUS_CONNECTION_STRING
  - name: handlerTimeoutInSec
    value: 120
  - name: timeoutInSec
    value: 5
  - name: lockDurationInSec
    value: 3
  - name: lockRenewalInSec
    value: 2
  - name: defaultMessageTimeToLiveInSec
    value: 2592000 # 30 * 24 * 60 * 60 
  - name: maxConcurrentHandlers
    value: 20
  - name: publishMaxRetries
    value: 100
  # - name: publishInitialRetryInternalInMs
  #   value: 10
  - name: maxDeliveryCount
    value: 10
  - name: maxActiveMessages
    value: 20
  - name: disableEntityManagement
    value: "true"
auth:
  secretStore: local-secret-store